[build]
  command = "npm install && npm install --save-dev @types/react @types/react-dom typescript && npm run build"
  publish = "out"

  [build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"